language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - POST_COMMAND=codecov -e TOX_ENV
install:
  - pip install tox-travis
script:
  - tox
branches:
  only:
    - master
#after_success:
#  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
