language: python
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - POST_COMMAND=codecov -e TOX_ENV
install:
  - pip install tox-travis
script:
  - tox
branches:
  only:
    - master
#after_success:
#  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
