language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install --user -r requirements-test.txt
script:
  - pytest --cov=pynws/
  - pylint pynws
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
