"""Layer enums"""
from pynws.backports.enum import StrEnum


class Layer(StrEnum):
    """Forecast layers"""

    TEMPERATURE = "temperature"
    DEWPOINT = "dewpoint"
    MAX_TEMPERATURE = "maxTemperature"
    MIN_TEMPERATURE = "minTemperature"
    RELATIVE_HUMIDITY = "relativeHumidity"
    APPARENT_TEMPERATURE = "apparentTemperature"
    HEAT_INDEX = "heatIndex"
    WIND_CHILL = "windChill"
    SKY_COVER = "skyCover"
    WIND_DIRECTION = "windDirection"
    WIND_SPEED = "windSpeed"
    WIND_GUST = "windGust"
    WEATHER = "weather"
    HAZARDS = "hazards"
    PROBABILITY_OF_PRECIPITATION = "probabilityOfPrecipitation"
    QUANTITATIVE_PRECIPITATION = "quantitativePrecipitation"
    ICE_ACCUMULATION = "iceAccumulation"
    SNOWFALL_AMOUNT = "snowfallAmount"
    SNOW_LEVEL = "snowLevel"
    CEILING_HEIGHT = "ceilingHeight"
    VISIBILITY = "visibility"
    TRANSPORT_WIND_SPEED = "transportWindSpeed"
    TRANSPORT_WIND_DIRECTION = "transportWindDirection"
    MIXING_HEIGHT = "mixingHeight"
    HAINES_INDEX = "hainesIndex"
    LIGHTNING_ACTIVITY_LEVEL = "lightningActivityLevel"
    TWENTY_FOOT_WIND_SPEED = "twentyFootWindSpeed"
    TWENTY_FOOT_WIND_DIRECTION = "twentyFootWindDirection"
    WAVE_HEIGHT = "waveHeight"
    WAVE_PERIOD = "wavePeriod"
    WAVE_DIRECTION = "waveDirection"
    PRIMARY_SWELL_HEIGHT = "primarySwellHeight"
    PRIMARY_SWELL_DIRECTION = "primarySwellDirection"
    SECONDARY_SWELL_HEIGHT = "secondarySwellHeight"
    SECONDARY_SWELL_DIRECTION = "secondarySwellDirection"
    WAVE_PERIOD2 = "wavePeriod2"
    WIND_WAVE_HEIGHT = "windWaveHeight"
    DISPERSION_INDEX = "dispersionIndex"
    PRESSURE = "pressure"
    PROBABILITY_OF_TROPICAL_STORM_WINDS = "probabilityOfTropicalStormWinds"
    PROBABILITY_OF_HURRICANE_WINDS = "probabilityOfHurricaneWinds"
    POTENTIAL_OF_15MPH_WINDS = "potentialOf15mphWinds"
    POTENTIAL_OF_25MPH_WINDS = "potentialOf25mphWinds"
    POTENTIAL_OF_35MPH_WINDS = "potentialOf35mphWinds"
    POTENTIAL_OF_45MPH_WINDS = "potentialOf45mphWinds"
    POTENTIAL_OF_20MPH_WIND_GUSTS = "potentialOf20mphWindGusts"
    POTENTIAL_OF_30MPH_WIND_GUSTS = "potentialOf30mphWindGusts"
    POTENTIAL_OF_40MPH_WIND_GUSTS = "potentialOf40mphWindGusts"
    POTENTIAL_OF_50MPH_WIND_GUSTS = "potentialOf50mphWindGusts"
    POTENTIAL_OF_60MPH_WIND_GUSTS = "potentialOf60mphWindGusts"
    GRASSLAND_FIRE_DANGER_INDEX = "grasslandFireDangerIndex"
    PROBABILITY_OF_THUNDER = "probabilityOfThunder"
    DAVIS_STABILITY_INDEX = "davisStabilityIndex"
    ATMOSPHERIC_DISPERSION_INDEX = "atmosphericDispersionIndex"
    LOW_VISIBILITY_OCCURRENCE_RISK_INDEX = "lowVisibilityOccurrenceRiskIndex"
    STABILITY = "stability"
    RED_FLAG_THREAT_INDEX = "redFlagThreatIndex"
